### ISSUE TITLE
Laravel 10 move to "module" in package.json breaks lighthouse run

### ISSUE THREAD

**Issue by Jonnx** [spatie/lighthouse-php#22]
Laravel recently witched to modules for the default package.json: https://github.com/laravel/laravel/commit/d3b2eada8618f8608c755137acc1741ec74771dc

When using a fresh laravel install with this package, you get an obscure error message:

```

   Spatie\Lighthouse\Exceptions\CouldNotRunLighthouse  Could not run Lighthouse. Error : `file://vendor/spatie/lighthouse-php/bin/lighthouse.js:4
        const arguments = JSON.parse(process.argv.slice(2));
              ^^^^^^^^^

SyntaxError: Unexpected eval or arguments in strict mode
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:117:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:337:14)
    at async link (node:internal/modules/esm/module_job:70:21)
```

This can be resolved by updating the package.json with:

```
{
    "private": true,
    "type": "commonjs",
    ...
}
```

Not sure if this is a long term solution but a work around. I may give updating the lighhouse.js file a shot this weekend.

**Comment by Jonnx** [comment]
making the change to "commonjs" in the package.json file breaks the vite build process

**Comment by Jonnx** [comment]
here is a pr to create compatibility with the laravel 10 changes in the package.json: https://github.com/spatie/lighthouse-php/pull/23

**Comment by Jonnx** [comment]
saw the test runs (and failures) and updated the PR with the following changes:
- named the lighthouse file correctly (.mjs extension)
- fixed code style with pint command

**Comment by freekmurze** [comment]
Will be handled in #23

**Comment by Jonnx** [comment]
linking this for visibility: https://github.com/spatie/lighthouse-php/pull/26

**Comment by Jonnx** [comment]
any thoughts on merging or closing #26 to resolve this issue for new laravel projects?
