### ISSUE TITLE
Always runs as mobile despite the formFactor

### ISSUE THREAD

**Issue by dudelisius** [spatie/lighthouse-php#38]
The documentation states that setting the formFactor will generate to either Mobile or Desktop; https://spatie.be/docs/lighthouse-php/v1/usage/configuring-a-run#content-specifying-the-form-factor

It also mentions that the default is Desktop, but I think that has changed to Mobile over the last few years.

Running the report always runs as Mobile, despite setting the form factor. See the attached image for the report settings.

```
$result = LighthouseCheck::url('https://laravel.com')
            ->formFactor(FormFactor::Desktop)
            ->run()
            ->saveHtml($localReportPath);
```

            
<img width="867" alt="Screenshot 2024-03-01 at 12 39 16" src="https://github.com/spatie/lighthouse-php/assets/394451/33f89a6c-2f32-47a1-ad3b-d2c7bb13729b">

**Comment by freekmurze** [comment]
Mmm, strange! If you need this fixed fast, do send a PR 👍

**Comment by freekmurze** [comment]
Will be handled in #42
